### ISSUE TITLE
Compatibility with 2022.1

### ISSUE THREAD

**Issue by maicol07** [Roboroads/laravel-tinker#136]
Hi,

currently the plugin is incompatible with PHPStorm 2022.1. Can you update it?

Thanks

**Comment by Roboroads** [comment]
Wow is it? I havn't received an email from JB telling me any compatibility issues.. Oh well, Imma look into it :)

**Comment by Roboroads** [comment]
Looks like it's compatible, but I set an upper bound to compatible jetbrains versions. I've tries to remove the uppen bound so the plugin won't just go out of date without serious compatibility issues.

**Comment by maicol07** [comment]
:+1: thank you! Do we have to wait for the plugin to be approved by Jetbrains?

**Comment by Roboroads** [comment]
Yup - as always :) But they usually apporve within 2 days.

**Comment by Roboroads** [comment]
Does the update work for you now?

**Comment by MuathIbnHassan** [comment]
it seems that 2.3.2 is not compatible with 2022.1

as it appears here: https://plugins.jetbrains.com/plugin/14957-laravel-tinker/versions/stable/158032

the version 2.3.2 compatibility range is 2021.2 — 2021.2.4

**Comment by Roboroads** [comment]
That might very well be because it's not out yet.

**Comment by MuathIbnHassan** [comment]
I am using 2022.1

The update were not avaliable at the store
I tried to uninstall it, then searching again
I cannot find it
i cannot find it in the store and the

I did try to download it as file then installing it from disk but this error appear :

![Laravel Tinker](https://user-images.githubusercontent.com/44880589/154025424-d18ed97d-df27-418e-8b01-5343fec264ef.png)

Plugin 'Laravel Tinker' (version '2.3.2') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is PS-221.4165.156

**Comment by Roboroads** [comment]
As you can see, that doesn't make any sense!

**Comment by MuathIbnHassan** [comment]
Any update?

**Comment by Roboroads** [comment]
2.3.3 should roll out any minute fixing the compatibility issue :)

Needs to be checked by JB ofc.

**Comment by Roboroads** [comment]
Just checked, 2.3.3 works now in 2022.1 EAP :D
Also: it won't go out of date anymore unless there's compatibility issues with a next version somewhere ^^
