### ISSUE TITLE
Tinker parameters

### ISSUE THREAD

**Issue by makroxyz** [Roboroads/laravel-tinker#26]
Please add the possibility to open tinker with params like --env or any other custom param

**Comment by Roboroads** [comment]
You can put them in your interpreter settings:
![image](https://user-images.githubusercontent.com/4398301/95999502-3bd88300-0e36-11eb-9748-b72ed5f903e7.png)

**Comment by makroxyz** [comment]
In Laravel you can start tinker with --env parameter to change environment.

Using https://github.com/tenancy there is another Tinker parameter --tenant to start tinker in a specific tenant which is almost "required"

It would be great to start your plugin with custom parameters or make different profiles...

**Comment by Roboroads** [comment]
@makroxyz I'm working on a settings page in which you can add these params.
Note that I actually don't call `php artisan tinker`, but rather `php -r <tinker init code> <your code>`.

**Comment by Roboroads** [comment]
For this featore to actually work I need to run de code through actual tinker. I *can* run code through tinker by changing the execution lines to what i have done [here](https://github.com/Roboroads/laravel-tinker/blob/wip/running-through-tinker/src/main/resources/scripts/tinker_run.php).

The problem here is that, in a tinker session, the  return value of the last command is displayed (neatly). This approach does not do that.

I need a little help with how I could do something like this.
