### ISSUE TITLE
Use the built-in "Scratches and Consoles" to store Tinker consoles.

### ISSUE THREAD

**Issue by mortenscheel** [Roboroads/laravel-tinker#39]
The action "Start new Tinker console" is a bit misleading since it doesn't actually start a new console, but rather reuses the previous one.

The ability to create multiple Tinker console files (and name them) would be a really nice feature.
I don't know where the plugin currently stores the console content, but I suppose the most intuitive place would be in the IDEs "Scratches and Consoles".

**Comment by Roboroads** [comment]
I like this idea, currently i'm saving it in the cache of the plugin on a per-project basis. Now we have the settings window there is a way to have a setting "Always reopen last window" and a seperate "start new console" button.

**Comment by majonathany** [comment]
Yes, I agree, I use the Tinker plugin multiple times a day and would like to save snippets without creating a PHP class that I have to pipeline into Laravel or the autoloader. But I find myself commenting things out too much in Tinker and it can get messy since I don't have a place to store my console files.

**Comment by Roboroads** [comment]
Good news - I just (3 mins ago) figured out how to do this with scratch files. It had been bothering me for weeks but it's coming in 2.0!

**Comment by Roboroads** [comment]
This is done, will be in the v2.0.0 release!
