### ISSUE TITLE
How to kill a frozen Tinker console's process?

### ISSUE THREAD

**Issue by majonathany** [Roboroads/laravel-tinker#41]
**Bug description**
When loading a large file (something like 600KB of json), the terminal tinker loads it fine, but the plugin to PHPStorm freezes up and there is no way from inside the GUI to kill the process. How do I kill the window? It does not seem that `killall -9 php` works. The only way to close this process is to close PHPStorm and reload completely.

**To Reproduce**
I loaded a 650KB 5 level nested JSON file, and it could not echo out the output.

**Expected behavior**
It should have displayed the JSON, or, display an error message if it was too large.

**Screenshots**
![image](https://user-images.githubusercontent.com/16457491/102080363-54d0c680-3ddc-11eb-93ab-b5e767606826.png)

**Environment (please complete the following information):**
 - IDE & Version: [e.g. PHPStorm 2020.2.4]
 - PHP Version: 7.3.21
 - OS: Mac OS X Big Sur, MacBook Pro 2018
 - Laravel Tinker plugin version : 1.3.0
 - Interpreter Type: Local
 - Laravel Version: 6.20.4
 - Tinker version: 2.5.0

**Additional context**
I'm not sure if this is something wrong with my machine or not - or if it's a known bug.

**Comment by Roboroads** [comment]
You _should_ be able to click the (x) on the bottom of your screen where it sais "executing tinker console". 

Sorry for answering late - I completely missed the notification.

**Comment by 4unkur** [comment]
@Roboroads do you mean the progress bar:

![Tinker Console 2021-04-07 12-00-15](https://user-images.githubusercontent.com/7892851/113818076-156a2380-9799-11eb-9e96-5cdeb94c40cd.jpg)

If so, then the provided solution does not solve the problem, because there is progress running.
My code is executed but for some reason the output is blank and it's no longer shown even if I try to execute something else in a new tinker console.

(The code with sleep function was used to screenshot the progress bar, my code was different)

**Comment by majonathany** [comment]
Hm, I recall trying various things but I couldn't get the process to stop. A few days after, I had purchased the Tinkerwell paid IDE plugin, and I haven't had any problems parsing extremely large data structures, so I'm not sure if that could resolve the problem.

**Comment by Roboroads** [comment]
I have done a couple of updates after this bug was reported. If the x is not working ill have to check for another solution.If tinkerwell is more in in line with your expextations - thats fine too. I'm just a single developer provinding you an opensource alternative which hopefully does enough. The guys at tinkerwell are a company that can spend hours a day in the software 🤷‍♂️

**Comment by majonathany** [comment]
I apologize, I really appreciate the software, it is an amazing tool. Tinkerwell is rather expensive, so I might come back to this plugin someday. I had no issues using this with smaller amounts of data and quick scripts, it was really quite nice. Thank you for building this!

**Comment by Roboroads** [comment]
Currently - what I do.

```while (!processHandler.isProcessTerminated) {
    Thread.sleep(250)
    try {
        progressIndicator.checkCanceled()
    } catch (ex: ProcessCanceledException) {
        processHandler.waitFor(5000)
        throw ex
    }
}```

Wait 0.25 seconds, check if the x has been pressed, if yes, wait for 5 seconds and then throw an exception. Honoustly, I haven't had a clue to do this properly yet.

**Comment by Roboroads** [comment]
![image](https://user-images.githubusercontent.com/4398301/114164736-f0f28080-992b-11eb-8f2e-9ff8d3d2a9fb.png)
I might have found it.
