### ISSUE TITLE
Error - reusing same file for all projects

### ISSUE THREAD

**Issue by emargareten** [Roboroads/laravel-tinker#43]
**Bug description**
Plugin is reusing same console for all projects (getting other projects snippets in new project)
Also getting an IDE error

**To Reproduce**
Opened tinker console in new project

**Expected behavior**
Create separate console for each project

**Screenshots**
![image](https://user-images.githubusercontent.com/46111162/107144618-0f94c500-6945-11eb-8639-d6e73cfc883e.png)

**Environment**
 - IDE & Version: PHPStorm 2020.3.2
 - PHP Version: 7.4|8.0
 - OS: Windows 10
 - Laravel Tinker plugin version : 1.3.1
 - Interpreter Type: Local
 - Laravel Version: 8.26.1
 - Tinker version: 2.6.0

**Comment by Roboroads** [comment]
Did you possibly have 2 projects open at the same time? If so we can test if thats the problem.Tinker cache is saved per-project in the .idea folder of that project. I'm very unsure how your second project got the cache file from another project since this is a native ide feature.Op 7 feb. 2021 12:11 schreef emargareten <notifications@github.com>:
Bug description
Plugin is reusing same console for all projects (getting other projects snippets in new project)
Also getting an IDE error
To Reproduce
Opened tinker console in new project
Expected behavior
Create separate console for each project
Screenshots

Environment
IDE & Version: PHPStorm 2020.3.2PHP Version: 7.4|8.0OS: Windows 10Laravel Tinker plugin version : 1.3.1Interpreter Type: LocalLaravel Version: 8.26.1Tinker version: 2.6.0

**Comment by emargareten** [comment]
@Roboroads That's right I did have 2 projects open at the same time, I just tried closing all projects and opened only one and did get the expected results 👍

**Comment by Roboroads** [comment]
Good. I just figured out how to use scratchfiles instead of LightVirtualFiles so this problem might be a thing of the past then :D
