### ISSUE TITLE
Ability to run statements individually

### ISSUE THREAD

**Issue by bfinlay** [Roboroads/laravel-tinker#45]
**Is your feature request related to a problem? Please describe.**
Currently, all statements in the tinker console are executed when the run button is clicked or the shortcut key's activated.  I most often use tinker when exploring possibilities and debugging a command.   Sometimes there a sequence of steps before that to load initial conditions.   When in the artisan console, the results of previous statements are generally stored in variables that are used in later steps.   So in artisan console while developing a line (perhaps a complex query builder) I only need to modify and retry that one line instead of re-execute all lines.

**Describe the solution you'd like**
One solution would be to feature multiple run buttons in the left hand gutter, one per statement.   This would be similar to how PHPStorm presents PHPUnit tests, where you can execute tests individually.  

PHPStorm also uses this technique in the http client (file->new->http request).  The HTTP client separates individual requests with a '###' line.   A similar idea could be used in this tinker plugin to separate groups of statements that we might want to rerun collectively.   For example, sometimes I am working on a database query and then processing the collection it returns.  As I modify the query I also need to rerun the collection.   

**Describe alternatives you've considered**
An alternative would be the technique that PHPStorm uses for database consoles.  you select which sql you want to execute by cursor position for a single statement or by highlighting multiple statements, and then press the execute button to run that selection

**Comment by Roboroads** [comment]
For this to work a tinker session should be kept open. Deserializing the current memory and reserializing it is not something PHP and Laravel is built for.

That's going to be a hard one, I think, since I'm only using tinker *code*, not `php artisan tinker` itself. (actually it's more like `php -r '<contents of tinker_run.php>' 'your code'`) I'm never doing readline for any of the execution. It's the way web-tinker works as well.

If you know a way and PRer it i'm definitely willing to include this feature into this plugin :)
